from setuptools import setup

setup(
    name='locust',
    version='',
    packages=['venv.Lib.site-packages.zmq', 'venv.Lib.site-packages.zmq.log', 'venv.Lib.site-packages.zmq.ssh',
              'venv.Lib.site-packages.zmq.auth', 'venv.Lib.site-packages.zmq.auth.asyncio',
              'venv.Lib.site-packages.zmq.green', 'venv.Lib.site-packages.zmq.green.eventloop',
              'venv.Lib.site-packages.zmq.sugar', 'venv.Lib.site-packages.zmq.tests',
              'venv.Lib.site-packages.zmq.tests.asyncio', 'venv.Lib.site-packages.zmq.utils',
              'venv.Lib.site-packages.zmq.asyncio', 'venv.Lib.site-packages.zmq.backend',
              'venv.Lib.site-packages.zmq.backend.cffi', 'venv.Lib.site-packages.zmq.backend.cython',
              'venv.Lib.site-packages.zmq.devices', 'venv.Lib.site-packages.zmq.eventloop',
              'venv.Lib.site-packages.zmq.eventloop.minitornado',
              'venv.Lib.site-packages.zmq.eventloop.minitornado.platform', 'venv.Lib.site-packages.cffi',
              'venv.Lib.site-packages.idna', 'venv.Lib.site-packages.click', 'venv.Lib.site-packages.flask',
              'venv.Lib.site-packages.flask.json', 'venv.Lib.site-packages.gevent',
              'venv.Lib.site-packages.gevent._ffi', 'venv.Lib.site-packages.gevent.libev',
              'venv.Lib.site-packages.gevent.libuv', 'venv.Lib.site-packages.gevent.tests',
              'venv.Lib.site-packages.gevent.testing', 'venv.Lib.site-packages.gevent.resolver',
              'venv.Lib.site-packages.jinja2', 'venv.Lib.site-packages.locust', 'venv.Lib.site-packages.locust.rpc',
              'venv.Lib.site-packages.locust.test', 'venv.Lib.site-packages.locust.util',
              'venv.Lib.site-packages.certifi', 'venv.Lib.site-packages.chardet', 'venv.Lib.site-packages.chardet.cli',
              'venv.Lib.site-packages.msgpack', 'venv.Lib.site-packages.urllib3', 'venv.Lib.site-packages.urllib3.util',
              'venv.Lib.site-packages.urllib3.contrib', 'venv.Lib.site-packages.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.urllib3.packages', 'venv.Lib.site-packages.urllib3.packages.rfc3986',
              'venv.Lib.site-packages.urllib3.packages.backports',
              'venv.Lib.site-packages.urllib3.packages.ssl_match_hostname', 'venv.Lib.site-packages.requests',
              'venv.Lib.site-packages.werkzeug', 'venv.Lib.site-packages.werkzeug.debug',
              'venv.Lib.site-packages.werkzeug.contrib', 'venv.Lib.site-packages.werkzeug.wrappers',
              'venv.Lib.site-packages.werkzeug.middleware', 'venv.Lib.site-packages.pycparser',
              'venv.Lib.site-packages.pycparser.ply', 'venv.Lib.site-packages.markupsafe',
              'venv.Lib.site-packages._pydev_imps', 'venv.Lib.site-packages.itsdangerous',
              'venv.Lib.site-packages._pydev_bundle', 'venv.Lib.site-packages.pydev_ipython',
              'venv.Lib.site-packages._pydevd_bundle', 'venv.Lib.site-packages._pydevd_bundle._debug_adapter',
              'venv.Lib.site-packages.pydevd_plugins', 'venv.Lib.site-packages.pydevd_plugins.extensions',
              'venv.Lib.site-packages._pydev_runfiles', 'venv.Lib.site-packages._pydevd_frame_eval',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.idna',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pytoml',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.certifi',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.chardet.cli',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.msgpack',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.util',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.backports',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.req',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.vcs',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.utils',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.models',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.commands',
              'venv.Lib.site-packages.pip-10.0.1-py3.7.egg.pip._internal.operations',
              'venv.Lib.site-packages.pydevd_concurrency_analyser', 'venv.pydevd_attach_to_process.winappdbg',
              'venv.pydevd_attach_to_process.winappdbg.win32', 'venv.pydevd_attach_to_process.winappdbg.plugins'],
    url='',
    license='',
    author='Minhmo',
    author_email='',
    description=''
)
